deployment:
  build-version: ${env:JWIZARD_CORE_BUILD_VERSION:UNKNOWN}
  last-build-date: ${env:JWIZARD_CORE_BUILD_DATE:UNKNOWN}

db:
  username: ${vault:V_MYSQL_USERNAME}
  password: ${vault:V_MYSQL_PASSWORD}
  driver-class-name: com.mysql.cj.jdbc.Driver

vault:
  kv:
    backend: jwizard
    default-context: common
    application-name: core

jda:
  secret-token: ${vault:V_JDA_SECRET}
  default-activity: tracks
  splashes:
    enabled: true
    interval-sec: 5
    elements:
      - Welcome!
      - I am
      - a magic
      - Discord
      - bot
      - and I can
      - play
      - songs
      - and
      - much
      - more...
  gateway-intents:
    - DIRECT_MESSAGES
    - GUILD_MESSAGES
    - GUILD_MESSAGE_REACTIONS
    - GUILD_VOICE_STATES
    - GUILD_MESSAGE_TYPING
    - GUILD_MEMBERS
    - MESSAGE_CONTENT
  cache-flags:
    enabled:
      - MEMBER_OVERRIDES
      - VOICE_STATE
    disabled:
      - ACTIVITY
      - CLIENT_STATUS
      - EMOJI
      - ONLINE_STATUS
      - SCHEDULED_EVENTS
      - STICKER
  color:
    primary: 0x4E5058
    danger: 0xEF4444
  interaction:
    message:
      max-embeds: 10
      action-row:
        max-rows: 5
        max-components-in-row: 5
      component:
        disable-delay-sec: 840 # 14 min
    slash:
      autocomplete:
        max-options: 25
  exception:
    segment-size: 100
    url-refer-template: '%s/error-codes/%d'
  superuser-permissions:
    - ADMINISTRATOR
    - MANAGE_SERVER

link:
  website: https://jwizard.pl
  repository: https://github.com/jwizard-bot
  docs: '%s/docs'
  command: '%s/command/%s'

lavalink:
  timeout-ms: 5000
  search:
    content-prefix: 'ytmsearch: %s'

radio:
  playback:
    extended-link: 'https://www.youtube.com/results?search_query=%s'

s3:
  region: eu-central-1
  path-style-access-enabled: true

i18n:
  default-language: pl
  revalidate-cache-sec: 10800 # 3 hours
  resources:
    remote:
      - i18n-modules/messages
      - i18n-args/messages
      - i18n-commands/messages
    local:
      - i18n-action/messages
      - i18n-audio/messages
      - i18n-exception/messages
      - i18n-response/messages
      - i18n-system/messages
      - i18n-util/messages
      - i18n-voting/messages
