vault:
  kv:
    application-names:
      - core
      - ${cmd:jda.shards.name}

jda:
  secret-token: ${vault:V_JDA_SECRET}
  sharding:
    fragment:
      min-id: ${vault:V_MIN_SHARD_ID}
      max-id: ${vault:V_MAX_SHARD_ID}
  instance:
    prefix: ${vault:V_JDA_INSTANCE_PREFIX}
  default-activity: tracks
  splashes:
    enabled: true
    interval-sec: 5
    elements:
      - Welcome!
      - I am
      - a magic
      - Discord
      - bot
      - and I can
      - play
      - songs
      - and
      - much
      - more...
  gateway-intents:
    - DIRECT_MESSAGES
    - GUILD_MESSAGES
    - GUILD_MESSAGE_REACTIONS
    - GUILD_VOICE_STATES
    - GUILD_MESSAGE_TYPING
    - GUILD_MEMBERS
    - MESSAGE_CONTENT
  cache-flags:
    enabled:
      - MEMBER_OVERRIDES
      - VOICE_STATE
    disabled:
      - ACTIVITY
      - CLIENT_STATUS
      - EMOJI
      - ONLINE_STATUS
      - SCHEDULED_EVENTS
      - STICKER
  color:
    primary: ${vault:V_JDA_PRIMARY_COLOR}
    danger: 0xEF4444
  interaction:
    message:
      max-embeds: 10
      action-row:
        max-rows: 5
        max-components-in-row: 5
      component:
        disable-delay-sec: 840 # 14 min
    slash:
      autocomplete:
        max-options: 25
  exception:
    segment-size: 100
    url-refer-template: '%s/error-codes/%d'
  superuser-permissions:
    - ADMINISTRATOR
    - MANAGE_SERVER
  pagination:
    chunk-size: 8

link:
  website: https://jwizard.pl
  repository: https://github.com/jwizard-bot
  status: https://status.jwizard.pl
  fragment:
    docs: '%s/docs'
    command: '%s/command/%s'
    shards: '%s/shards'

lavalink:
  timeout-ms: 5000
  search:
    content-prefix: 'ytmsearch: %s'

radio:
  playback:
    extended-link: 'https://www.youtube.com/results?search_query=%s'
