db:
  jdbc: jdbc:mysql://localhost:${env:ENV_MYSQL_PORT:8762}/jwizard-db

vault:
  url: http://localhost:8761
  token: ${env:ENV_VAULT_TOKEN}

jda:
  name: JWizard DEV

service:
  api-url: http://localhost:8765

s3:
  public-api-url: http://localhost:8763/jwizard-static
  host-url: http://localhost:8763
  access-key: ${vault:V_S3_USERNAME}
  secret-key: ${vault:V_S3_PASSWORD}
  root-bucket: jwizard-static
