db:
  jdbc: jdbc:mysql://localhost:${env:ENV_MYSQL_PORT:8762}/jwizard-db

vault:
  url: http://localhost:8761
  token: ${env:ENV_VAULT_TOKEN}

jda:
  name: JWizard DEV

lavalink:
  nodes:
    - LAVA-NODE-1::EUROPE::${vault:V_LAVA_NODE_1_TOKEN}::ws://localhost:8766
    - LAVA-NODE-2::EUROPE::${vault:V_LAVA_NODE_2_TOKEN}::ws://localhost:8767

service:
  api-url: http://localhost:8765
  front-url: http://localhost:8766

s3:
  host-url: http://localhost:8763
  access-key: ${vault:V_S3_USERNAME}
  secret-key: ${vault:V_S3_PASSWORD}
  root-bucket: jwizard-static
