db:
  jdbc: ${vault:V_MYSQL_JDBC}

vault:
  url: ${env:JWIZARD_CORE_VAULT_SERVER}
  token: ${env:JWIZARD_CORE_VAULT_TOKEN}

jda:
  name: JWizard

lavalink:
  nodes:
    - LAVA-NODE-1::EUROPE::${vault:V_LAVA_NODE_1_TOKEN}::wss://prod-node1.lava.jwizard.pl
    - LAVA-NODE-2::EUROPE::${vault:V_LAVA_NODE_2_TOKEN}::wss://prod-node2.lava.jwizard.pl

service:
  api-url: https://api.jwizard.pl
  front-url: https://jwizard.pl

s3:
  host-url: https://s3.api.miloszgilga.pl
  access-key: ${vault:V_S3_ACCESS_KEY}
  secret-key: ${vault:V_S3_SECRET_KEY}
  root-bucket: cdn.jwizard.pl
