deployment:
  build-version: ${env:JWIZARD_CORE_BUILD_VERSION:UNKNOWN}
  last-build-date: ${env:JWIZARD_CORE_BUILD_DATE:UNKNOWN}

db:
  username: ${vault:V_MYSQL_USERNAME}
  password: ${vault:V_MYSQL_PASSWORD}
  driver-class-name: com.mysql.cj.jdbc.Driver

vault:
  kv:
    backend: jwizard
    default-context: common
    application-name: core

jda:
  secret-token: ${vault:V_JDA_SECRET}
  default-activity: tracks
  pagination:
    max-elements-per-page: 20
    menu-alive-sec: 60
  splashes:
    enabled: true
    interval-sec: 5
    elements:
      - Welcome!
      - I am
      - a magic
      - Discord
      - bot
      - and I can
      - play
      - songs
      - and
      - much
      - more...
  gateway-intents:
    - DIRECT_MESSAGES
    - GUILD_MESSAGES
    - GUILD_MESSAGE_REACTIONS
    - GUILD_VOICE_STATES
    - GUILD_MESSAGE_TYPING
    - GUILD_MEMBERS
    - MESSAGE_CONTENT
  cache-flags:
    enabled:
      - MEMBER_OVERRIDES
      - VOICE_STATE
    disabled:
      - ACTIVITY
      - CLIENT_STATUS
      - EMOJI
      - ONLINE_STATUS
      - SCHEDULED_EVENTS
      - STICKER
  color:
    primary: 0xFFFFFF
    secondary: 0x000000
    tint: 0x505050
    danger: 0xEF4444

s3:
  region: eu-central-1
  path-style-access-enabled: true

i18n:
  default-language: pl
  revalidate-cache-sec: 10800 # 3 hours
  resources:
    remote:
      - i18n-modules/messages
      - i18n-args/messages
      - i18n-commands/messages
    local:
      - i18n-action/messages
      - i18n-audio/messages
      - i18n-exception/messages
      - i18n-response/messages
      - i18n-system/messages
      - i18n-util/messages
      - i18n-voting/messages
