spring:
  devtools:
    livereload:
      port: 35732
    restart:
      log-condition-evaluation-delta: false

jwizard:
  api-host: http://localhost:8670
  app-name: JWizard DEV
  app-icon-path: classpath:assets/logo/dark.png

logging:
  file:
    path: .log/dev
