spring:
  application:
    name: jwizard-core
  banner:
    location: classpath:spring/banner.txt
  config:
    import:
      - optional:vault://
  cloud:
    vault:
      uri: ${ENV_VAULT_URI:http://localhost:8761}
      token: ${ENV_VAULT_TOKEN}
      authentication: TOKEN
      kv:
        backend: jwizard
        default-context: common
        application-name: ${spring.application.name}

jwizard:
  default-activity: tracks
  splashes:
    enabled: true
    interval-sec: 5
    list:
      - Welcome!
      - I am
      - a magic
      - Discord
      - bot
      - and I can
      - play
      - songs
      - and
      - much
      - more...
  pagination:
    max-elements-per-page: 20
    menu-alive-sec: 60
  i18n:
    locale-bundles:
      - i18n-res/messages
