spring:
  devtools:
    add-properties: false
  datasource:
    url: ${V_MYSQL_JDBC}
  cloud:
    vault:
      uri: ${JWIZARD_CORE_VAULT_SERVER}
      token: ${JWIZARD_CORE_VAULT_TOKEN}
      authentication: TOKEN
      kv:
        backend: jwizard
        default-context: common
        application-name: core
  config:
    import:
      - optional:vault://

jwizard:
  api-host: http://localhost:6061
  app-name: JWizard
  app-icon-path: light.png
