spring:
  devtools:
    livereload:
      port: 35732
    restart:
      log-condition-evaluation-delta: false

jwizard:
  api-host: http://localhost:8670
  instance:
    auth-token: ${V_JDA_DEV_SECRET}
    app-id: ${V_JDA_DEV_APP_ID}
  app-name: JWizard DEV
  app-icon-path: classpath:assets/logo/dark.png

logging:
  file:
    path: .log/dev
