spring:
  devtools:
    add-properties: false
  cloud:
    vault:
      uri: https://vault.miloszgilga.pl
      token: ${JWIZARD_CORE_VAULT_TOKEN}
      authentication: TOKEN
      kv:
        backend: jwizard
        default-context: common
        application-name: core
  config:
    import:
      - optional:vault://

jwizard:
  api-host: http://localhost:6061
  app-name: JWizard
  app-icon-path: classpath:assets/logo/light.png

logging:
  file:
    path: .log/prod
