spring:
  application:
    name: jwizard-core
  banner:
    location: classpath:spring/banner.txt
  datasource:
    username: ${V_MYSQL_USERNAME}
    password: ${V_MYSQL_PASSWORD}

jwizard:
  deployment:
    build-version: ${JWIZARD_CORE_BUILD_VERSION:UNKNOWN}
    last-build-date: ${JWIZARD_CORE_BUILD_DATE:UNKNOWN}
  default-activity: tracks
  instance:
    auth-token: ${V_JDA_SECRET}
    app-id: ${V_JDA_APP_ID}
    default-language: 'pl'
  splashes:
    enabled: true
    interval-sec: 5
    list:
      - Welcome!
      - I am
      - a magic
      - Discord
      - bot
      - and I can
      - play
      - songs
      - and
      - much
      - more...
  pagination:
    max-elements-per-page: 20
    menu-alive-sec: 60
  i18n:
    locale-bundles:
      - i18n-res/messages
