spring:
  devtools:
    livereload:
      port: 35732
    restart:
      log-condition-evaluation-delta: false
  datasource:
    url: jdbc:mysql://localhost:${ENV_MYSQL_PORT:8762}/jwizard-db
  cloud:
    vault:
      uri: ${ENV_VAULT_URI:http://localhost:8761}
      token: ${ENV_VAULT_TOKEN}
      authentication: TOKEN
      kv:
        backend: jwizard
        default-context: common
        application-name: core
  config:
    import:
      - optional:vault://

jwizard:
  api-host: http://localhost:8670
  app-name: JWizard DEV
  app-icon-path: dark.png

logging:
  file:
    path: .log/dev
