spring:
  application:
    name: jwizard-core
  banner:
    location: classpath:spring/banner.txt

jwizard:
  default-activity: tracks
  instance:
    auth-token: ${V_JDA_SECRET}
    app-id: ${V_JDA_APP_ID}
  splashes:
    enabled: true
    interval-sec: 5
    list:
      - Welcome!
      - I am
      - a magic
      - Discord
      - bot
      - and I can
      - play
      - songs
      - and
      - much
      - more...
  pagination:
    max-elements-per-page: 20
    menu-alive-sec: 60
  i18n:
    locale-bundles:
      - i18n-res/messages
