[versions]
kotlinVersion = "2.0.20"
springVersion = "6.1.12"
logbackVersion = "1.5.7"
slf4jApiVersion = "2.0.16"
kamlVersion = "0.61.0"
dotenvVersion = "2.2.0"
shadowJarVersion = "8.1.1"

[libraries]
kotlin = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlinVersion" }
kotlinReflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlinVersion" }
springContext = { module = "org.springframework:spring-context", version.ref = "springVersion" }
logbackCore = { module = "ch.qos.logback:logback-core", version.ref = "logbackVersion" }
logbackClassic = { module = "ch.qos.logback:logback-classic", version.ref = "logbackVersion" }
slf4jApi = { module = "org.slf4j:slf4j-api", version.ref = "slf4jApiVersion" }
kaml = { module = "com.charleskorn.kaml:kaml", version.ref = "kamlVersion" }
dotEnv = { module = "io.github.cdimascio:dotenv-java", version.ref = "dotenvVersion" }

[plugins]
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlinVersion" }
kotlinSpring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlinVersion" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinVersion" }
shadowJar = { id = "com.github.johnrengelman.shadow", version.ref = "shadowJarVersion" }
