#
# Copyright (c) 2023 by MILOSZ GILGA <http://miloszgilga.pl>
#
# File name: libs.versions.toml
# Last modified: 23/02/2023, 16:51
# Project name: jwizard-discord-bot
#
# Licensed under the MIT license; you may not use this file except in compliance with the License.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
# documentation files (the "Software"), to deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to the following conditions:
#
# THE ABOVE COPYRIGHT NOTICE AND THIS PERMISSION NOTICE SHALL BE INCLUDED IN ALL
# COPIES OR SUBSTANTIAL PORTIONS OF THE SOFTWARE.
#

# libs.versions.toml
# refer to build.gradle 3rd part libraries script file

[versions]
jda                 = '4.4.1_353'
lavaPlayer          = '1.4.0'
jdaUtilities        = '1.24.1'

mysqlDriver         = '8.0.31'
hibernate           = '6.1.6.Final'
liquibase           = '3.10.3'

lombok              = '1.18.26'
log4j               = '2.20.0'
jUnit               = '5.8.1'
springFramework     = '6.0.5'
springVault         = '3.0.0'
snakeYaml           = '1.33'
commonsText         = '1.10.0'
commonsValidator    = '1.7'
dotEnv              = '5.2.2'
commonsCli          = '1.5.0'
reflections         = '0.10.2'
apacheHttpClient    = '4.5.14'

shadowJarPackager   = '7.1.2'

[libraries]
jda                     = { module = 'net.dv8tion:JDA',                             version.ref = 'jda' }
lavaplayer              = { module = 'com.github.walkyst:lavaplayer-fork',          version.ref = 'lavaPlayer' }
jdautilities            = { module = 'pw.chew:jda-chewtils',                        version.ref = 'jdaUtilities' }

mysql-driver            = { module = 'mysql:mysql-connector-java',                  version.ref = 'mysqlDriver' }
hibernate               = { module = 'org.hibernate:hibernate-core',                version.ref = 'hibernate' }
c3p0pools               = { module = 'org.hibernate.orm:hibernate-c3p0',            version.ref = 'hibernate' }
liquibase               = { module = 'org.liquibase:liquibase-core',                version.ref = 'liquibase' }

lombok                  = { module = 'org.projectlombok:lombok',                    version.ref = 'lombok' }
log4j-core              = { module = 'org.apache.logging.log4j:log4j-core',         version.ref = 'log4j' }
log4j-api               = { module = 'org.apache.logging.log4j:log4j-api',          version.ref = 'log4j' }
log4j-slf4j             = { module = 'org.apache.logging.log4j:log4j-slf4j-impl',   version.ref = 'log4j' }
spring-context          = { module = 'org.springframework:spring-context',          version.ref = 'springFramework' }
spring-vault            = { module = 'org.springframework.vault:spring-vault-core', version.ref = 'springVault' }
snakeyaml               = { module = 'org.yaml:snakeyaml',                          version.ref = 'snakeYaml' }
commons-text            = { module = 'org.apache.commons:commons-text',             version.ref = 'commonsText' }
commons-validator       = { module = 'commons-validator:commons-validator',         version.ref = 'commonsValidator' }
commons-cli             = { module = 'commons-cli:commons-cli',                     version.ref = 'commonsCli' }
dotenv                  = { module = 'io.github.cdimascio:java-dotenv',             version.ref = 'dotEnv' }
reflections             = { module = 'org.reflections:reflections',                 version.ref = 'reflections' }
apache-httpclient       = { module = 'org.apache.httpcomponents:httpclient',        version.ref = 'apacheHttpClient' }
junit-api               = { module = 'org.junit.jupiter:junit-jupiter-api',         version.ref = 'jUnit' }
junit-engine            = { module = 'org.junit.jupiter:junit-jupiter-engine',      version.ref = 'jUnit' }

[plugins]
shadow-packager         = { id     = 'com.github.johnrengelman.shadow',             version.ref = 'shadowJarPackager' }
